name: Build SwanStation RetroArch Core (Windows x64)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Clone SwanStation repo and dependencies
      run: |
        git clone --recursive https://github.com/libretro/swanstation.git
        cd swanstation
        git submodule update --init --recursive

    - name: Build SwanStation Core
      run: |
        cd swanstation
        mkdir build
        cd build
        cmake .. -G "Visual Studio 17 2022" -A x64
        cmake --build . --config Release

    - name: Upload built core as artifact
      uses: actions/upload-artifact@v2
      with:
        name: swanstation-core
        path: swanstation/build/Release/*.dll
